"use client";
/* import type { Metadata } from "next"; */
import { Inter } from "next/font/google";
import "./globals.css";
import { useState } from "react";
import Head from "next/head";
import Logo from "@/assets/logo.png"
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [activeMenuMovil, setActiveMenuMovil] = useState(true);
  return (
    <html lang="es">
      <title>Nievas Angel Gabriel</title>
      <body className={`${inter.className} bg-gray-900`}>
        <nav
          className="w-full navbar"
        >
          <div className="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
            <div className="relative flex h-16 items-center justify-between z-40">
              <div className="absolute inset-y-0 left-0 flex items-center sm:hidden">
                <button
                  type="button"
                  className="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
                  aria-controls="mobile-menu"
                  aria-expanded="false"
                  onClick={() => setActiveMenuMovil(!activeMenuMovil)}
                >
                  <span className="absolute -inset-0.5"></span>
                  <span className="sr-only">Open main menu</span>

                  <svg
                    className="block h-6 w-6"
                    style={{ display: activeMenuMovil ? "block" : "hidden" }}
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    aria-hidden="true"
                  >
                    <path
                      d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"
                    />
                  </svg>
                </button>
              </div>
              <div className="flex flex-1 items-center justify-center align-center sm:items-stretch sm:justify-start">
                <div className="flex flex-shrink-0 items-center">
                  <Image
                    className="h-14 w-auto"
                    src={Logo}
                    alt="Your Company"
                  />
                </div>
                <div className="hidden sm:ml-6 sm:block content-center w-full">
                  <div className="flex space-x-4 ">
                    {/*             
                    <!-- Current: "bg-gray-900 text-white", 
                    Default: "text-gray-300 hover:bg-gray-700 
                    hover:text-white" -->
                     */}{" "} 
                    <a
                      href="#proyects"
                      className="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium h-full"
                    >
                      Proyectos
                    </a>
                    <a
                      href="#studies"
                      className="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium"
                    >
                      Estudios
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* <!-- Mobile menu, show/hide based on menu state. --> */}
          <div className="sm:hidden" id="mobile-menu" hidden={activeMenuMovil}>
            <div className="space-y-1 px-2 pb-3 pt-2">
              {/* <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" --> */}

              <a
                href="#"
                className="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium"
              >
                Proyectos
              </a>
              <a
                href="#"
                className="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium"
              >
                Estudios
              </a>
              {/* <a
                href="#"
                className="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium"
              >
                Calendar
              </a> */}
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
